# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/MyNuget.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'donet build'
  inputs:
    command: 'build'
    projects: '**/MyNuget.csproj'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    projects: '**/MyNuget.csproj'
    arguments: '--no-build --configuration $(buildConfiguration)'